In [1]:
import itertools

In [6]:
middlegen = itertools.product(range(7), repeat=3)

In [14]:
next(middlegen)

(0, 1, 0)

In [3]:
import numpy as np

a = np.array(
    [
        [False, False, True, False, False, False],
        [False, False, False, True, False, False],
        [False, False, False, False, True, False],
        [False, False, False, False, False, True],
    ]
)

In [21]:
np.diagonal(a, 3)

array([False, False, False])

In [42]:
m = np.random.choice([1, 2, 4], 10)

In [43]:
m

array([2, 4, 2, 2, 4, 1, 4, 4, 1, 2])

In [26]:
possibility = (4, 1, 2)

In [44]:
palette = (m == possibility[0])
palette

array([False,  True, False, False,  True, False,  True,  True, False,
       False])

In [45]:
for idx, feature in enumerate(possibility[1:]):
    palette = palette[:-1] & (m[idx + 1:] == feature)

In [46]:
palette

array([False, False, False, False, False, False, False,  True])

In [38]:
np.array([True, False]) | np.array([True, True])

array([ True,  True])

In [1]:
from Backtesting.staticdata.options.tertiary_patterns.context import TertiaryController

In [9]:
tcontr = TertiaryController()
tertiary_data = np.random.choice([1, 2, 4], 372530)
tcontr.make_library(4, tertiary_data)

{(1, 1, 1, 1): 4683,
 (1, 1, 1, 2): 4694,
 (1, 1, 1, 4): 4721,
 (1, 1, 2, 1): 4671,
 (1, 1, 2, 2): 4706,
 (1, 1, 2, 4): 4538,
 (1, 1, 4, 1): 4581,
 (1, 1, 4, 2): 4654,
 (1, 1, 4, 4): 4672,
 (1, 2, 1, 1): 4680,
 (1, 2, 1, 2): 4556,
 (1, 2, 1, 4): 4538,
 (1, 2, 2, 1): 4625,
 (1, 2, 2, 2): 4529,
 (1, 2, 2, 4): 4716,
 (1, 2, 4, 1): 4475,
 (1, 2, 4, 2): 4597,
 (1, 2, 4, 4): 4519,
 (1, 4, 1, 1): 4734,
 (1, 4, 1, 2): 4570,
 (1, 4, 1, 4): 4458,
 (1, 4, 2, 1): 4520,
 (1, 4, 2, 2): 4554,
 (1, 4, 2, 4): 4661,
 (1, 4, 4, 1): 4650,
 (1, 4, 4, 2): 4480,
 (1, 4, 4, 4): 4705,
 (2, 1, 1, 1): 4683,
 (2, 1, 1, 2): 4553,
 (2, 1, 1, 4): 4639,
 (2, 1, 2, 1): 4519,
 (2, 1, 2, 2): 4557,
 (2, 1, 2, 4): 4561,
 (2, 1, 4, 1): 4625,
 (2, 1, 4, 2): 4539,
 (2, 1, 4, 4): 4622,
 (2, 2, 1, 1): 4650,
 (2, 2, 1, 2): 4526,
 (2, 2, 1, 4): 4684,
 (2, 2, 2, 1): 4581,
 (2, 2, 2, 2): 4570,
 (2, 2, 2, 4): 4509,
 (2, 2, 4, 1): 4539,
 (2, 2, 4, 2): 4607,
 (2, 2, 4, 4): 4586,
 (2, 4, 1, 1): 4579,
 (2, 4, 1, 2): 4597,
 (2, 4, 1, 4)

In [2]:
import timeit

In [3]:

stp = '''
import numpy as np
from Backtesting.staticdata.options.tertiary_patterns.context import TertiaryController
tcontr = TertiaryController()
tertiary_data = np.random.choice([1, 2, 4], 372530)
'''
timeit.timeit('tcontr.make_library(4, tertiary_data)',
              setup=stp
              , number=1000)


55.4454562

In [4]:
55.4454562/1000

0.0554454562

In [11]:
tcontr = TertiaryController()
tertiary_data = np.random.choice([1, 2, 4], 20)
raw_data = np.random.random(20)
tertiary_data

array([1, 1, 4, 1, 4, 2, 1, 1, 2, 1, 4, 1, 1, 2, 1, 2, 1, 1, 2, 2])

In [14]:
features = (1, 1, 2)
tcontr.sieve_library(tertiary_data, features)

array([False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False])

In [20]:
trunc_raw_data = raw_data[len(features)-1:]
trunc_raw_data

array([0.01179619, 0.15170507, 0.35403271, 0.35275156, 0.24750778,
       0.48890347, 0.01339017, 0.35083552, 0.26704599, 0.87083155,
       0.50697597, 0.36298652, 0.57686612, 0.54085175, 0.03525464,
       0.09327658, 0.1135149 , 0.54884779])

In [13]:
time_stamps = np.array( [0, 1, 5, 10, 15, 20, 30, 60, 120, 180, 240, 300, 1440, 2880])

In [29]:
features_idx = np.where(
    tcontr.sieve_library(
        tertiary_data, 
        features)
)
features_idx

(array([ 6, 11, 16], dtype=int64),)

In [82]:
selector = time_stamps.reshape(14, 1) + features_idx 
nanselector = np.where(selector < trunc_raw_data.size, True, np.nan)
nanselector

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1., nan],
       [ 1., nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [117]:
raw_selected = np.choose(selector, trunc_raw_data, mode='clip' )
raw_selected

array([[0.01339017, 0.36298652, 0.1135149 ],
       [0.35083552, 0.57686612, 0.54884779],
       [0.36298652, 0.1135149 , 0.54884779],
       [0.1135149 , 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779],
       [0.54884779, 0.54884779, 0.54884779]])

In [92]:
raw_nan_selected = raw_selected * nanselector
raw_nan_selected

array([[0.01339017, 0.36298652, 0.1135149 ],
       [0.35083552, 0.57686612, 0.54884779],
       [0.36298652, 0.1135149 ,        nan],
       [0.1135149 ,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan]])

In [94]:
diff_selected = raw_nan_selected - raw_nan_selected[0]
diff_selected

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.33744536,  0.2138796 ,  0.43533289],
       [ 0.34959635, -0.24947161,         nan],
       [ 0.10012474,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan]])

In [118]:
bin_nan_selected = ((diff_selected > 0) * nanselector)
bin_nan_selected

array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  0., nan],
       [ 1., nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [119]:
np.count_nonzero(bin_nan_selected, axis=1)

array([0, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [123]:
total_time_features = np.count_nonzero(~np.isnan(bin_nan_selected), axis=1)
total_time_features

array([3, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [124]:
total_uptrend_features = np.nansum(bin_nan_selected, axis=1)
total_uptrend_features

array([0., 3., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
time_stamps.reshape(time_stamps.size, 1)

array([[   0],
       [   1],
       [   5],
       [  10],
       [  15],
       [  20],
       [  30],
       [  60],
       [ 120],
       [ 180],
       [ 240],
       [ 300],
       [1440],
       [2880]])

In [125]:
np.array([total_uptrend_features, total_time_features])

array([[0., 3., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 3., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
tc = TertiaryController()
tc.raw_m1_csv = np.random.random(20)
tc.tertiary_m1 = tc.into_tertiles()
tc.tertiary_m1

array([2, 4, 1, 4, 4, 4, 4, 1, 2, 1, 4, 2, 1, 2, 2, 1, 2, 1, 4, 1])

In [20]:
features = ( 2, 1, 2)

In [7]:
tc.extract_trends(features)

array([[1., 2., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 3., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
tc.raw_m1_csv

array([0.22855333, 0.58691452, 0.21217817, 0.43137363, 0.25888812,
       0.33509194, 0.99403873, 0.98114596, 0.79131441, 0.56456119,
       0.26495355, 0.48640768, 0.17861234, 0.65093559, 0.32520457,
       0.33025767, 0.6428947 , 0.50817451, 0.74237086, 0.85023969])

In [21]:
def extract_trends(f, rd=None, td=None):

    trunc_raw_data = rd[len(f)-1:] # remove first unused bits of data from raw data
    print('trunc_raw_data\n', trunc_raw_data)
    features_idx = np.where(  # find indecis of where features accure
                    tc.sieve_library(
                        td, 
                        f)
                )
    print('features_idx\n', features_idx)
    selector = time_stamps.reshape(
        time_stamps.size, 1) + features_idx 
    print('selector\n', selector)
    nanselector = np.where(selector < trunc_raw_data.size, True, np.nan)
    print('nanselector\n', nanselector)
    raw_selected = np.take(trunc_raw_data, selector, mode='clip')
    raw_selected_choose = np.choose(selector, trunc_raw_data, mode='clip')
    print('raw_selected\n', raw_selected)
    print('raw_selected_choose\n', raw_selected_choose)
    raw_nan_selected = raw_selected * nanselector
    print('raw_nan_selected\n', raw_nan_selected)
    diff_selected = raw_nan_selected - raw_nan_selected[0]
    print('diff_selected\n', diff_selected)
    bin_nan_selected = ((diff_selected > 0) * nanselector)
    print('bin_nan_selected\n', bin_nan_selected)
    return np.array([
                    np.nansum(bin_nan_selected, axis=1),
                    np.count_nonzero(
                            ~np.isnan(bin_nan_selected), 
                            axis=1)
                    ])

In [26]:
extract_trends(features, tc.raw_m1_csv, tc.tertiary_m1)

trunc_raw_data
 [0.16308079 0.61020906 0.87329148 0.7638266  0.57280084 0.06444324
 0.54914607 0.06422806 0.59899347 0.44434736 0.33654282 0.4567298
 0.45506269 0.10571744 0.5459125  0.41083335 0.77465666 0.02749227]
features_idx
 (array([11, 14], dtype=int64),)
selector
 [[  11   14]
 [  12   15]
 [  16   19]
 [  21   24]
 [  26   29]
 [  31   34]
 [  41   44]
 [  71   74]
 [ 131  134]
 [ 191  194]
 [ 251  254]
 [ 311  314]
 [1451 1454]
 [2891 2894]]
nanselector
 [[ 1.  1.]
 [ 1.  1.]
 [ 1. nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]]
raw_selected
 [[0.4567298  0.5459125 ]
 [0.45506269 0.41083335]
 [0.77465666 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]
 [0.02749227 0.02749227]]
raw_selecte

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
import numpy as np
from Backtesting.staticdata.options.tertiary_patterns.context import TertiaryController

In [6]:
tc = TertiaryController()
tc.load_random(17000)

array([2, 4, 4, ..., 4, 1, 1])

In [7]:
tc.make_trend_lib(1)

{(1,): array([[   0., 4706., 4699., 4694., 4665., 4713., 4753., 4741., 4664.,
         4673., 4641., 4638., 4364., 3933.],
        [5667., 5666., 5665., 5664., 5663., 5661., 5658., 5648., 5624.,
         5603., 5582., 5566., 5183., 4706.]]),
 (2,): array([[   0., 2800., 2845., 2816., 2854., 2821., 2853., 2813., 2808.,
         2801., 2784., 2750., 2601., 2383.],
        [5666., 5666., 5666., 5664., 5663., 5662., 5659., 5646., 5627.,
         5607., 5591., 5566., 5190., 4704.]]),
 (4,): array([[   0.,  955.,  904.,  927.,  974.,  938.,  932.,  965.,  919.,
          924.,  922.,  949.,  859.,  790.],
        [5667., 5667., 5664., 5662., 5659., 5657., 5653., 5646., 5629.,
         5610., 5587., 5568., 5187., 4710.]])}

In [8]:
tc.iscompatible((1,4,4), (1, 4, 4))

True

In [24]:
a = np.array([[0., 0., 1., 1., 0., 0., 0., 0., 0., 34., 0., 0., 0., 0.],
              [1., 1., 1., 1., 0., 0., 0., 0., 0., 64., 0., 0., 0., 0.]])

b = np.array([[0., 0., 1., 1., 0., 0., 0., 0., 0., 4., 0., 0., 0., 0.],
              [1., 1., 1., 1., 0., 0., 0., 0., 0., 11., 0., 0., 0., 0.]])

In [25]:
a += b
a

array([[ 0.,  0.,  2.,  2.,  0.,  0.,  0.,  0.,  0., 38.,  0.,  0.,  0.,
         0.],
       [ 2.,  2.,  2.,  2.,  0.,  0.,  0.,  0.,  0., 75.,  0.,  0.,  0.,
         0.]])

In [18]:
np.zeros((2, time_stamps.size))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.choose(np.random.randint(0, 31, 100) , np.random.random(31))

array([0.89934513, 0.21695749, 0.23856967, 0.23856967, 0.47622442,
       0.05089272, 0.89934513, 0.14090473, 0.86982321, 0.85076915,
       0.14090473, 0.25147145, 0.44612227, 0.14374696, 0.25147145,
       0.88867929, 0.47622442, 0.39870113, 0.98929408, 0.21695749,
       0.89934513, 0.00693754, 0.70530529, 0.14535839, 0.14090473,
       0.98929408, 0.14374696, 0.23856967, 0.22385932, 0.54903833,
       0.00693754, 0.89934513, 0.14374696, 0.88867929, 0.0188182 ,
       0.47622442, 0.22385932, 0.89934513, 0.42520112, 0.44612227,
       0.00693754, 0.45429886, 0.98929408, 0.44612227, 0.25147145,
       0.05089272, 0.44612227, 0.7549312 , 0.16963963, 0.98929408,
       0.00693754, 0.25147145, 0.89934513, 0.89934513, 0.44612227,
       0.31451409, 0.86982321, 0.25147145, 0.05089272, 0.99703603,
       0.86982321, 0.99469374, 0.05089272, 0.44612227, 0.99469374,
       0.09009502, 0.05089272, 0.31451409, 0.39870113, 0.86982321,
       0.14090473, 0.85076915, 0.01924369, 0.16963963, 0.59765

In [24]:
selector = np.array([[ 1,3 ,   9],
 [   2  ,  4 ,  10],
 [   6  ,  8,   14],
 [  11  , 13,   19],
 [  16,   18,   24],
 [  21 ,  23 ,  29],
 [  31,   33 ,  39],
 [  61 ,  63  , 69],
 [ 121,  123 , 129],
 [ 181 , 183 , 189],
 [ 241 , 243,  249],
 [ 301,  303  ,309],
 [1441,1443, 1449],
 [2881, 2883 ,2889]])