In [1]:
from Backtesting.staticdata.options.local_tertiary_patterns.context import LocalTertiaryLibrary
import numpy as np

In [2]:
raw = np.random.random(20)
raw

array([0.72036135, 0.31816752, 0.40610058, 0.64365054, 0.80680538,
       0.3559598 , 0.16866352, 0.84453812, 0.81496648, 0.42586977,
       0.55653212, 0.30719129, 0.48584848, 0.7301825 , 0.37266028,
       0.83992116, 0.85207181, 0.48584429, 0.11251398, 0.13622833])

In [3]:
extractor = LocalTertiaryLibrary()

In [6]:
extractor.extract_local_trends((4, 1), rd=raw, td=np.array([4, 1]))

[[   0]
 [   1]
 [   5]
 [  10]
 [  15]
 [  20]
 [  30]
 [  60]
 [ 120]
 [ 180]
 [ 240]
 [ 300]
 [1440]
 [2880]]
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]] [[nan]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]


array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
extractor.make_local_lib(l=2, rd=raw)

(1, 1) [2] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(1, 2) [2] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(1, 4) [2] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(2, 1) [2] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(2, 2) [2] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(2, 4) [2] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(4, 1) [2] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(4, 2) [2] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(4, 4) [2] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(1, 1) [4 1] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0

{(1,
  1): array([[ 0.,  0.,  5., 11.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.],
        [17., 17., 17., 17.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.]]),
 (1,
  2): array([[ 0.,  2.,  5., 10., 11.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.],
        [24., 24., 24., 17., 17.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.]]),
 (1,
  4): array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.],
        [16., 16., 12., 12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.]]),
 (2,
  1): array([[ 0.,  3.,  6.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.],
        [13., 13., 12.,  4.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.]]),
 (2,
  2): array([[ 0.,  0.,  7.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.],
        [17., 17., 17.,  8.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.]]),
 (2,
  4): array([[ 0.,  1.,  2.,  3.,  0.,  0.,  