In [1]:
from TheoryStatsMath.BruteForce import asymetric_random_walk_precision_limit
from TheoryStatsMath.BruteForce import test

In [109]:
import numpy as np
import math


def asymetric_random_walk_with_ci(s: float, U: float, 
                                          L: float, i: float, 
                                          d: float, p: float, 
                                          stability_threshold=1e-3,
                                          confidence_level=0.99):
    """
   Running random walk simulation until percentage is in specific precision.

   :param float s: starting point
   :param float U: Upper limit
   :param float L: Lowe limit
   :param float i: increament step size
   :param float d: decriment step size
   :param float p: probability of increament
   :param int: precs: precision to stop after floating point
   """
    z = 2.576

    upper_barrier_hits = 0
    lower_barrier_hits = 0

    while True:
        current_position = s
        while True:
            current_position += np.random.choice([i, -d], p=[p, 1-p])

            if current_position >= U:
                upper_barrier_hits += 1
                break
            elif current_position <= L:
                lower_barrier_hits += 1
                break
        
        total_trials = upper_barrier_hits + lower_barrier_hits
        if total_trials > 1000:
            p_hat = upper_barrier_hits/ total_trials
            margin_of_error = z * math.sqrt((p_hat * (1 - p_hat)) / total_trials)
            # print(p_hat, margin_of_error, stability_threshold)
            if margin_of_error < stability_threshold:
                break

    return p_hat

In [110]:
starting_point = 22.247808
upper_boundary = 30.571629
lower_boundary = 21.91124
increment = 3.983074
decrement = 4.500463
probability = 0.502347

asymetric_random_walk_with_ci(starting_point,
upper_boundary ,
lower_boundary,
increment,
decrement,
probability)

0.16951549263208826

In [77]:
import time

def asymetric_random_walk_with_time(s: float, U: float, 
                                          L: float, i: float, 
                                          d: float, p: float, 
                                          runtime):
    """
   Running random walk simulation until percentage is in specific precision.

   :param float s: starting point
   :param float U: Upper limit
   :param float L: Lowe limit
   :param float i: increament step size
   :param float d: decriment step size
   :param float p: probability of increament
   :param int: precs: precision to stop after floating point
   """

    upper_barrier_hits = 0
    lower_barrier_hits = 0
    st = time.time()
    while time.time() - st < runtime:
        current_position = s
        while True:
            current_position += np.random.choice([i, -d], p=[p, 1-p])

            if current_position >= U:
                upper_barrier_hits += 1
                break
            elif current_position <= L:
                lower_barrier_hits += 1
                break
        
    total_trials = upper_barrier_hits + lower_barrier_hits
    p_hat = upper_barrier_hits/ total_trials
            

    return p_hat, total_trials

In [79]:
asymetric_random_walk_with_time(14.8607,27.1852, 8.17544, 2.26917, 1.74059, 0.325786, 10)

(0.03934786626589235, 102801)

In [ ]:
from collections import deque
import numpy as np


def asymetric_random_walk_with_rolling_average(s: float, U: float, 
                                          L: float, i: float, 
                                          d: float, p: float, 
                                          chunk = 10, window_size=100):
    """
   Running random walk simulation until percentage is in specific precision.

   :param float s: starting point
   :param float U: Upper limit
   :param float L: Lowe limit
   :param float i: increament step size
   :param float d: decriment step size
   :param float p: probability of increament
   :param int: precs: precision to stop after floating point
   """

    rolling_window = deque(maxlen=window_size)

    while True:
        upper_barrier_hits = 0
        lower_barrier_hits = 0
        for i in range(chunk):
            current_position = s
            while True:
                current_position += np.random.choice([i, -d], p=[p, 1-p])

                if current_position >= U:
                    upper_barrier_hits += 1
                    break
                elif current_position <= L:
                    lower_barrier_hits += 1
                    break
            
        total_trials = upper_barrier_hits + lower_barrier_hits
        p_hat = upper_barrier_hits/ total_trials
        rolling_window.append(p_hat)
                

    return p_hat, total_trials

In [1]:
number_of_sha_possibilities = 1.16 * (10 ** 77)
number_of_atoms_on_the_earth = 1.33 * (10 ** 50)

number_of_sha_possibilities / number_of_atoms_on_the_earth

8.721804511278193e+26

In [5]:
import math

math.gcd(3140, 7438)


2

In [84]:
import pandas as pd
from sklearn.model_selection import train_test_split


# Step 1: Load the CSV file
# Replace 'your_data.csv' with the path to your CSV file
df = pd.read_csv(r"C:\Users\MSI\source\repos\2Bsamples\2Bsamples\2Bdata.csv")

# Step 2: Split the data into input features (X) and target output (y)
X = df.iloc[:, :-1].values  # First 6 columns as input features
y = df.iloc[:, -1].values   # Last column as the output/target

# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [87]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()
model.fit(X_train, y_train)

# Step 5: Predict using the model
y_pred = model.predict(X_test)

# Step 6: Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Optionally, print model coefficients and intercept
print(f"Coefficients: {model.coef_}")
print(f"Intercept: {model.intercept_}")

Mean Squared Error: 0.024239660788274612
R-squared: 0.8554155210548371
Coefficients: [ 0.01873647 -0.00928131 -0.00980456  0.06874524 -0.06810132  1.18739869]
Intercept: -0.09603624477601919


In [89]:
model.predict([[5.0, 10.0, 0.0, 1.0, 1.0, 0.5]])

array([0.49917623])

Random numbers: x = 20.1807, y = 21.8991, z = 29.2009
Random steps 2.76376 and 4.41717
Random percentage 0.533935
Total trials 1125257
Resulting Percentage 0.216406

In [92]:
model.predict([[21.8991, 50.2009, 20.1807, 2.76376, 4.41717,  0.533935]])

array([0.17365637])

In [106]:
df = pd.read_csv(r"C:\Users\MSI\source\repos\2Bsamples\2Bsamples\2Bdata.csv")

X = df.loc[df.iloc[:, 7] == 1, df.columns[0]].values.reshape(-1, 1)

y = df.loc[df.iloc[:, 7] == 1, df.columns[1:3]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

array([[22.392311],
       [18.701168],
       [26.459783],
       [ 4.907457],
       [ 6.957941],
       [ 3.183869],
       [28.154766],
       [16.758873],
       [16.308209],
       [21.903685],
       [ 6.61004 ],
       [22.247808],
       [ 3.159989],
       [ 1.156211],
       [17.004557],
       [ 1.289727],
       [ 6.351093],
       [ 8.703828],
       [17.066543],
       [ 5.983162]])

In [107]:
modelEnv = LinearRegression()
modelEnv.fit(X_train, y_train)

# Step 5: Predict using the model
y_pred = modelEnv.predict(X_test)

# Step 6: Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Optionally, print model coefficients and intercept
print(f"Coefficients: {modelEnv.coef_}")
print(f"Intercept: {modelEnv.intercept_}")

Mean Squared Error: 10.67325547082183
R-squared: 0.7254513888721971
Coefficients: [[0.55281695]
 [1.01139138]]
Intercept: [17.85461569 -0.76335827]


In [108]:
modelEnv.predict([[1]])

array([[18.40743264,  0.24803311]])